version: '3.8'
services:
  # Server service
  chatserver:
    build:
      context: .
      dockerfile: ChatServer/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - chatapp-network

  # Client services
  chatclient:
    build:
      context: .
      dockerfile: ChatClient/Dockerfile
    depends_on:
      - chatserver
    networks:
      - chatapp-network

  consoleclient:
    build:
      context: .
      dockerfile: ConsoleClient/Dockerfile
    depends_on:
      - chatserver
    networks:
      - chatapp-network

# Define a bridge network for inter-container communication
networks:
  chatapp-network:
    driver: bridge