version: '3.8'
services:
  chatserver:
    build:
      context: .
      dockerfile: ./ChatServer/Dockerfile  # Use explicit relative path
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

