version: '3.8'

services:
  chatserver:
    build: .
    ports:
      - "7891:7891"  # Map host port to container port
    restart: always  # Restart policy for the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # Optional: Set environment variables if needed